Add starship profile
Also, allow custom debian installations.

diff --git a/function/platform/install b/function/platform/install
--- a/function/platform/install
+++ b/function/platform/install
@@ -22,19 +22,23 @@ platform::install() {
       fi
       ;;
     'debian')
-      if ! variable::empty? "$apt_package"; then
-        if apt list -i | grep -q git; then
-          echo "[apt] $program already installed ..."
+      if function::exists? debian_install; then
+        debian_install
+      else
+        if ! variable::empty? "$apt_package"; then
+          if apt list -i | grep -q git; then
+            echo "[apt] $program already installed ..."
+            return 0
+          fi
+
+          echo "[apt] installing $program ..."
+          if ! sudo apt update && sudo apt -y install $apt_package; then
+            echo "[apt] failed to install $program"
+            return 1
+          fi
+
           return 0
         fi
-
-        echo "[apt] installing $program ..."
-        if ! sudo apt update && sudo apt -y install $apt_package; then
-          echo "[apt] failed to install $program"
-          return 1
-        fi
-
-        return 0
       fi
       ;;
   esac
