Account for potential failures to install
Also, check if program is already installed via apt.

diff --git a/function/platform/install b/function/platform/install
--- a/function/platform/install
+++ b/function/platform/install
@@ -7,19 +7,34 @@ platform::install() {
   case $platform in
     'mac')
       if ! variable::empty? "$homebrew_formula"; then
-        if ! brew list | grep $homebrew_formula > /dev/null ; then
-          echo "[homebrew] installing $program ..."
-          brew update && brew install $homebrew_formula && return 0
-        else
-          echo "[$program] already installed ..."
+        if brew list | grep $homebrew_formula > /dev/null ; then
+          echo "[homebrew] $program already installed ..."
           return 0
         fi
+
+        echo "[homebrew] installing $program ..."
+        if ! brew update && brew install $homebrew_formula; then
+          echo "[homebrew] failed to install $program"
+          return 1
+        fi
+
+        return 0
       fi
       ;;
     'debian')
       if ! variable::empty? "$apt_package"; then
+        if apt list -i | grep -q git; then
+          echo "[apt] $program already installed ..."
+          return 0
+        fi
+
         echo "[apt] installing $program ..."
-        sudp apt update && sudo apt -y install $apt_package && return 0
+        if ! sudo apt update && sudo apt -y install $apt_package; then
+          echo "[apt] failed to install $program"
+          return 1
+        fi
+
+        return 0
       fi
       ;;
   esac
