Make platform::safe_link safer
It now aborts if:
* $from does not exist
* $to.old exists

diff --git a/function/platform/safe_link b/function/platform/safe_link
--- a/function/platform/safe_link
+++ b/function/platform/safe_link
@@ -8,20 +8,31 @@ platform::safe_link() {
   local from=$2
   local to=$3
 
-  if path::exists $to; then
-    echo "[$what] $to exists; do you want to replace it (Yes / No)? "
-    case $(prompt::yes_or_no) in
-      Yes)
-        echo "[$what] Old $to will be moved to $to.old"
-        mv $to $to.old
-        echo "[$what] $to will be linked to $from"
-        ln -s $from $to
-        ;;
-      No)
-        echo "[$what] $to will not be linked"
-        ;;
-    esac
-  else
-    ln -s $from $to
+  echo "[$what] $to will be linked to $from"
+
+  if ! path::exists "$from"; then
+    echo "[$what] $from does not exist; aborting!"
+    return 1
   fi
+
+  if path::exists "$to"; then
+    if path::exists "$to.old"; then
+      echo "[$what] both $to and $to.old already exist; aborting!"
+      return 1
+    fi
+
+    echo "[$what] $to exists; do you want to replace it (Yes / No)?"
+    case $(prompt::yes_or_no) in
+    Yes)
+      echo "[$what] old $to will be moved to $to.old"
+      mv "$to" "$to.old"
+      ;;
+    No)
+      echo "[$what] $to will not be linked"
+      return 1
+      ;;
+    esac
+  fi
+
+  ln -s "$from" "$to"
 }
